{
 "title": "Greenplum集群监控状态图",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "version",
    "query": "label_values(greenplum_cluster_state, version)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "greenplum_cluster_uptime", "legendFormat": "运行时间" }
   ]
  },
  {
   "title": "Master可达",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "greenplum_up" }
   ]
  },
  {
   "title": "Standby同步",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "greenplum_cluster_sync" }
   ]
  },
  {
   "title": "当前连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_cluster_total_connections"
    }
   ]
  },
  {
   "title": "数据节点剩余存储空间",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "greenplum_node_segment_disk_free_mb_size",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "账号总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_server_users_total_count"
    }
   ]
  },
  {
   "title": "在线账号数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "greenplum_cluster_total_online_user_count"
    }
   ]
  },
  {
   "title": "当前客户端数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "greenplum_cluster_total_client_count"
    }
   ]
  },
  {
   "title": "事务提交率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_server_database_transition_commit_percent_rate"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_server_database_hit_cache_percent_rate"
    }
   ]
  },
  {
   "title": "Segment实例在线状态",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "greenplum_node_segment_status" }
   ]
  },
  {
   "title": "Segment实例同步模式",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "greenplum_node_segment_mode" }
   ]
  },
  {
   "title": "数据库占用空间和表数量",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "greenplum_node_database_table_total_count"
    },
    {
     "expr": "greenplum_node_database_name_mb_size"
    }
   ]
  },
  {
   "title": "表和索引占用磁盘空间",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 17 },
   "targets": [
    { "expr": "greenplum_cluster_table_size" },
    { "expr": "greenplum_cluster_index_size" }
   ]
  },
  {
   "title": "活动连接数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "greenplum_cluster_active_connections",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "greenplum_cluster_active_connections_per_user",
     "legendFormat": "{{usename}}"
    }
   ]
  },
  {
   "title": "客户端连接数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "连接个数" }
   ],
   "targets": [
    {
     "expr": "greenplum_cluster_active_connections_per_client{client!=\"\"}",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "数据倾斜",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "greenplum_cluster_table_skew" }
   ]
  },
  {
   "title": "慢查询前10名",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "greenplum_cluster_slow_query" }
   ]
  },
  {
   "title": "需要analyze的表",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "greenplum_cluster_table_need_analyze"
    }
   ]
  },
  {
   "title": "需要vacuum的表",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    { "expr": "table_bloat" }
   ]
  },
  {
   "title": "数据库锁状态监听实时列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "greenplum_server_locks_table_detail"
    }
   ]
  }
 ]
}